# deployment.yaml

---
# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
---
# 2. ConfigMap - configuração do Nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app-prod
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
      }

      location /api/ {
        proxy_pass http://backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
# 3. Deployment - Frontend React
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mquinteiro464/plantio20-frontend:v2
          ports:
            - containerPort: 80
---
# 4. Deployment - Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mquinteiro464/plantio20-backend:v1
          ports:
            - containerPort: 8080
---
# 5. Deployment - Nginx Proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
# 6. Service - Frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-prod
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
# 7. Service - Backend
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-prod
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
---
# 8. Service - Nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app-prod
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80