apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mquinteiro464/plantio20-backend:v1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://database-service:5432/mhqa_plantio
        - name: SPRING_DATASOURCE_USERNAME
          value: mhqa
        - name: SPRING_DATASOURCE_PASSWORD
          value: hk28gr20p1
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_APPLICATION_NAME
          value: mhqa_plantio
---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
